apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "product.fullname" . }}-config
  labels:
    {{- include "product.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.config.data | nindent 2 }}